// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: user.proto

package user

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 抢气球用户结构请求 方法名 BalloonGameUserinfo
type BalloonGameUserinfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *BalloonGameUserinfoReq) Reset() {
	*x = BalloonGameUserinfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalloonGameUserinfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalloonGameUserinfoReq) ProtoMessage() {}

func (x *BalloonGameUserinfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalloonGameUserinfoReq.ProtoReflect.Descriptor instead.
func (*BalloonGameUserinfoReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *BalloonGameUserinfoReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 抢气球用户结构返回
type BalloonGameUserinfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeadIconImageUrl string `protobuf:"bytes,1,opt,name=HeadIconImageUrl,proto3" json:"HeadIconImageUrl,omitempty"` // 头像url
	Nickname         string `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`                 // 昵称
	Gold             string `protobuf:"bytes,3,opt,name=Gold,proto3" json:"Gold,omitempty"`                         // 可用金币
	Code             int32  `protobuf:"varint,4,opt,name=Code,proto3" json:"Code,omitempty"`                        // 0 正常 -1 错误
	ErrorMsg         string `protobuf:"bytes,5,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`                 // 错误信息
}

func (x *BalloonGameUserinfoResp) Reset() {
	*x = BalloonGameUserinfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalloonGameUserinfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalloonGameUserinfoResp) ProtoMessage() {}

func (x *BalloonGameUserinfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalloonGameUserinfoResp.ProtoReflect.Descriptor instead.
func (*BalloonGameUserinfoResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *BalloonGameUserinfoResp) GetHeadIconImageUrl() string {
	if x != nil {
		return x.HeadIconImageUrl
	}
	return ""
}

func (x *BalloonGameUserinfoResp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *BalloonGameUserinfoResp) GetGold() string {
	if x != nil {
		return x.Gold
	}
	return ""
}

func (x *BalloonGameUserinfoResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BalloonGameUserinfoResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 用户金币变化 方法名 UserGoldEdit
type UserGoldEditReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`        // 用户id
	Genre int32  `protobuf:"varint,2,opt,name=Genre,proto3" json:"Genre,omitempty"` // 类型 1 加金币 2 减金币
	Gold  string `protobuf:"bytes,3,opt,name=Gold,proto3" json:"Gold,omitempty"`    // 金币数
	Type  string `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`    // 日志类型
}

func (x *UserGoldEditReq) Reset() {
	*x = UserGoldEditReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGoldEditReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGoldEditReq) ProtoMessage() {}

func (x *UserGoldEditReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGoldEditReq.ProtoReflect.Descriptor instead.
func (*UserGoldEditReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserGoldEditReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserGoldEditReq) GetGenre() int32 {
	if x != nil {
		return x.Genre
	}
	return 0
}

func (x *UserGoldEditReq) GetGold() string {
	if x != nil {
		return x.Gold
	}
	return ""
}

func (x *UserGoldEditReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// 用户金币变化返回
type UserGoldEditResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int32  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`        // 0 正常 -1  错误
	ErrorMsg string `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"` // 错误信息
	Gold     string `protobuf:"bytes,3,opt,name=Gold,proto3" json:"Gold,omitempty"`         // 当前剩余金币数
}

func (x *UserGoldEditResp) Reset() {
	*x = UserGoldEditResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGoldEditResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGoldEditResp) ProtoMessage() {}

func (x *UserGoldEditResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGoldEditResp.ProtoReflect.Descriptor instead.
func (*UserGoldEditResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserGoldEditResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserGoldEditResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *UserGoldEditResp) GetGold() string {
	if x != nil {
		return x.Gold
	}
	return ""
}

// 获取用户头像[社区详情]请求  方法名 GetUserNicknameHeadimgUrl
type GetUserNicknameHeadimgUrlReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *GetUserNicknameHeadimgUrlReq) Reset() {
	*x = GetUserNicknameHeadimgUrlReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserNicknameHeadimgUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserNicknameHeadimgUrlReq) ProtoMessage() {}

func (x *GetUserNicknameHeadimgUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserNicknameHeadimgUrlReq.ProtoReflect.Descriptor instead.
func (*GetUserNicknameHeadimgUrlReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserNicknameHeadimgUrlReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 获取用户头像[社区详情]返回
type GetUserNicknameHeadimgUrlResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeadIconImageUrl string `protobuf:"bytes,1,opt,name=HeadIconImageUrl,proto3" json:"HeadIconImageUrl,omitempty"` // 头像地址
	HeadIconAvatar   int32  `protobuf:"varint,2,opt,name=HeadIconAvatar,proto3" json:"HeadIconAvatar,omitempty"`    // 头像框装饰
	Nickname         string `protobuf:"bytes,3,opt,name=Nickname,proto3" json:"Nickname,omitempty"`                 // 昵称
	Exp              string `protobuf:"bytes,4,opt,name=Exp,proto3" json:"Exp,omitempty"`                           // 等级经验
	CharmExp         string `protobuf:"bytes,5,opt,name=CharmExp,proto3" json:"CharmExp,omitempty"`                 // 魅力经验值
	RichExp          string `protobuf:"bytes,6,opt,name=RichExp,proto3" json:"RichExp,omitempty"`                   // 财富经验
	PeerageLv        int32  `protobuf:"varint,7,opt,name=PeerageLv,proto3" json:"PeerageLv,omitempty"`              // 爵位等级
	Sex              int32  `protobuf:"varint,8,opt,name=Sex,proto3" json:"Sex,omitempty"`                          // 性别
	Birthday         int64  `protobuf:"varint,9,opt,name=Birthday,proto3" json:"Birthday,omitempty"`                // 生日
	Code             int32  `protobuf:"varint,10,opt,name=Code,proto3" json:"Code,omitempty"`                       // 0 正常 -1  错误
	ErrorMsg         string `protobuf:"bytes,11,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`                // 错误信息
}

func (x *GetUserNicknameHeadimgUrlResp) Reset() {
	*x = GetUserNicknameHeadimgUrlResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserNicknameHeadimgUrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserNicknameHeadimgUrlResp) ProtoMessage() {}

func (x *GetUserNicknameHeadimgUrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserNicknameHeadimgUrlResp.ProtoReflect.Descriptor instead.
func (*GetUserNicknameHeadimgUrlResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserNicknameHeadimgUrlResp) GetHeadIconImageUrl() string {
	if x != nil {
		return x.HeadIconImageUrl
	}
	return ""
}

func (x *GetUserNicknameHeadimgUrlResp) GetHeadIconAvatar() int32 {
	if x != nil {
		return x.HeadIconAvatar
	}
	return 0
}

func (x *GetUserNicknameHeadimgUrlResp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetUserNicknameHeadimgUrlResp) GetExp() string {
	if x != nil {
		return x.Exp
	}
	return ""
}

func (x *GetUserNicknameHeadimgUrlResp) GetCharmExp() string {
	if x != nil {
		return x.CharmExp
	}
	return ""
}

func (x *GetUserNicknameHeadimgUrlResp) GetRichExp() string {
	if x != nil {
		return x.RichExp
	}
	return ""
}

func (x *GetUserNicknameHeadimgUrlResp) GetPeerageLv() int32 {
	if x != nil {
		return x.PeerageLv
	}
	return 0
}

func (x *GetUserNicknameHeadimgUrlResp) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *GetUserNicknameHeadimgUrlResp) GetBirthday() int64 {
	if x != nil {
		return x.Birthday
	}
	return 0
}

func (x *GetUserNicknameHeadimgUrlResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserNicknameHeadimgUrlResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 获取用户社区关系请求 方法名 CommunityUserList
type CommunityUserListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyId string `protobuf:"bytes,1,opt,name=MyId,proto3" json:"MyId,omitempty"`
}

func (x *CommunityUserListReq) Reset() {
	*x = CommunityUserListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityUserListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityUserListReq) ProtoMessage() {}

func (x *CommunityUserListReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityUserListReq.ProtoReflect.Descriptor instead.
func (*CommunityUserListReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *CommunityUserListReq) GetMyId() string {
	if x != nil {
		return x.MyId
	}
	return ""
}

// 获取用户社区关系返回
type CommunityUserListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data     map[string]*CommunityUserinfo `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Code     int32                         `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`        // 0 正常 -1  错误
	ErrorMsg string                        `protobuf:"bytes,3,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"` // 错误信息
}

func (x *CommunityUserListResp) Reset() {
	*x = CommunityUserListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityUserListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityUserListResp) ProtoMessage() {}

func (x *CommunityUserListResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityUserListResp.ProtoReflect.Descriptor instead.
func (*CommunityUserListResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *CommunityUserListResp) GetData() map[string]*CommunityUserinfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CommunityUserListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommunityUserListResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 用户社区关系
type CommunityUserinfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type             int32  `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`                        // 1 互关 2 我关注他 3 他关注我 4 黑名单
	HeadIconImageUrl string `protobuf:"bytes,2,opt,name=HeadIconImageUrl,proto3" json:"HeadIconImageUrl,omitempty"` // 头像地址
	HeadIconAvatar   int32  `protobuf:"varint,3,opt,name=HeadIconAvatar,proto3" json:"HeadIconAvatar,omitempty"`    // 头像框装饰
	Nickname         string `protobuf:"bytes,4,opt,name=Nickname,proto3" json:"Nickname,omitempty"`                 // 昵称
	Exp              string `protobuf:"bytes,5,opt,name=Exp,proto3" json:"Exp,omitempty"`                           // 等级经验
	CharmExp         string `protobuf:"bytes,6,opt,name=CharmExp,proto3" json:"CharmExp,omitempty"`                 // 魅力经验值
	RichExp          string `protobuf:"bytes,7,opt,name=RichExp,proto3" json:"RichExp,omitempty"`                   // 财富经验
	PeerageLv        int32  `protobuf:"varint,8,opt,name=PeerageLv,proto3" json:"PeerageLv,omitempty"`              // 爵位等级
	Sex              int32  `protobuf:"varint,9,opt,name=Sex,proto3" json:"Sex,omitempty"`                          // 性别
	Birthday         int64  `protobuf:"varint,10,opt,name=Birthday,proto3" json:"Birthday,omitempty"`               // 生日
}

func (x *CommunityUserinfo) Reset() {
	*x = CommunityUserinfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityUserinfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityUserinfo) ProtoMessage() {}

func (x *CommunityUserinfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityUserinfo.ProtoReflect.Descriptor instead.
func (*CommunityUserinfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *CommunityUserinfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CommunityUserinfo) GetHeadIconImageUrl() string {
	if x != nil {
		return x.HeadIconImageUrl
	}
	return ""
}

func (x *CommunityUserinfo) GetHeadIconAvatar() int32 {
	if x != nil {
		return x.HeadIconAvatar
	}
	return 0
}

func (x *CommunityUserinfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CommunityUserinfo) GetExp() string {
	if x != nil {
		return x.Exp
	}
	return ""
}

func (x *CommunityUserinfo) GetCharmExp() string {
	if x != nil {
		return x.CharmExp
	}
	return ""
}

func (x *CommunityUserinfo) GetRichExp() string {
	if x != nil {
		return x.RichExp
	}
	return ""
}

func (x *CommunityUserinfo) GetPeerageLv() int32 {
	if x != nil {
		return x.PeerageLv
	}
	return 0
}

func (x *CommunityUserinfo) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *CommunityUserinfo) GetBirthday() int64 {
	if x != nil {
		return x.Birthday
	}
	return 0
}

// 获取我的关注请求 方法名 GetMyFollows
type GetMyFollowsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"` // 我的id
}

func (x *GetMyFollowsReq) Reset() {
	*x = GetMyFollowsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyFollowsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyFollowsReq) ProtoMessage() {}

func (x *GetMyFollowsReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyFollowsReq.ProtoReflect.Descriptor instead.
func (*GetMyFollowsReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetMyFollowsReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 获取我的关注返回
type GetMyFollowsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   []string `protobuf:"bytes,1,rep,name=UserId,proto3" json:"UserId,omitempty"`     // 我的关注用户列表
	Code     int32    `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`        // 0 正常 -1  错误
	ErrorMsg string   `protobuf:"bytes,3,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"` // 错误信息
}

func (x *GetMyFollowsResp) Reset() {
	*x = GetMyFollowsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyFollowsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyFollowsResp) ProtoMessage() {}

func (x *GetMyFollowsResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyFollowsResp.ProtoReflect.Descriptor instead.
func (*GetMyFollowsResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *GetMyFollowsResp) GetUserId() []string {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *GetMyFollowsResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetMyFollowsResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 获取用户信息请求 方法名 GetUserinfo
type GetUserinfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=Ids,proto3" json:"Ids,omitempty"` // 请求id 数组形式传递 获取一个和获取多人都用这个请求
}

func (x *GetUserinfoReq) Reset() {
	*x = GetUserinfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserinfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserinfoReq) ProtoMessage() {}

func (x *GetUserinfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserinfoReq.ProtoReflect.Descriptor instead.
func (*GetUserinfoReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserinfoReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// 获取用户信息返回
type GetUserinfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Userinfo `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"` // 返回数据 数组形式返回 1个就返回一个
}

func (x *GetUserinfoResp) Reset() {
	*x = GetUserinfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserinfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserinfoResp) ProtoMessage() {}

func (x *GetUserinfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserinfoResp.ProtoReflect.Descriptor instead.
func (*GetUserinfoResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserinfoResp) GetData() []*Userinfo {
	if x != nil {
		return x.Data
	}
	return nil
}

//用户信息
type Userinfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`                             // 用户主键id
	DisplayId        string   `protobuf:"bytes,2,opt,name=DisplayId,proto3" json:"DisplayId,omitempty"`               // 外显id
	DisplayIdLevel   int32    `protobuf:"varint,3,opt,name=DisplayIdLevel,proto3" json:"DisplayIdLevel,omitempty"`    // 靓号等级 默认为0 1,2,3 普通 精英 顶级
	HeadIconImageUrl string   `protobuf:"bytes,4,opt,name=HeadIconImageUrl,proto3" json:"HeadIconImageUrl,omitempty"` // 头像
	Nickname         string   `protobuf:"bytes,5,opt,name=Nickname,proto3" json:"Nickname,omitempty"`                 // 昵称
	Sex              int32    `protobuf:"varint,6,opt,name=Sex,proto3" json:"Sex,omitempty"`                          // 性别
	Birthday         int64    `protobuf:"varint,7,opt,name=Birthday,proto3" json:"Birthday,omitempty"`                // 生日
	FansCount        int32    `protobuf:"varint,8,opt,name=FansCount,proto3" json:"FansCount,omitempty"`              // 粉丝数量
	FollowCount      int32    `protobuf:"varint,9,opt,name=FollowCount,proto3" json:"FollowCount,omitempty"`          // 关注数量
	StarCount        int32    `protobuf:"varint,10,opt,name=StarCount,proto3" json:"StarCount,omitempty"`             // 被点赞数量
	Bag              *BagInfo `protobuf:"bytes,11,opt,name=Bag,proto3" json:"Bag,omitempty"`                          // 背包信息
	City             string   `protobuf:"bytes,12,opt,name=City,proto3" json:"City,omitempty"`                        // 城市
}

func (x *Userinfo) Reset() {
	*x = Userinfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Userinfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Userinfo) ProtoMessage() {}

func (x *Userinfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Userinfo.ProtoReflect.Descriptor instead.
func (*Userinfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *Userinfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Userinfo) GetDisplayId() string {
	if x != nil {
		return x.DisplayId
	}
	return ""
}

func (x *Userinfo) GetDisplayIdLevel() int32 {
	if x != nil {
		return x.DisplayIdLevel
	}
	return 0
}

func (x *Userinfo) GetHeadIconImageUrl() string {
	if x != nil {
		return x.HeadIconImageUrl
	}
	return ""
}

func (x *Userinfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Userinfo) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *Userinfo) GetBirthday() int64 {
	if x != nil {
		return x.Birthday
	}
	return 0
}

func (x *Userinfo) GetFansCount() int32 {
	if x != nil {
		return x.FansCount
	}
	return 0
}

func (x *Userinfo) GetFollowCount() int32 {
	if x != nil {
		return x.FollowCount
	}
	return 0
}

func (x *Userinfo) GetStarCount() int32 {
	if x != nil {
		return x.StarCount
	}
	return 0
}

func (x *Userinfo) GetBag() *BagInfo {
	if x != nil {
		return x.Bag
	}
	return nil
}

func (x *Userinfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type BagInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data           []*ItemInfo `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`                      // 背包信息
	RichExp        string      `protobuf:"bytes,2,opt,name=RichExp,proto3" json:"RichExp,omitempty"`                // 当前财富经验值
	CharmExp       string      `protobuf:"bytes,3,opt,name=CharmExp,proto3" json:"CharmExp,omitempty"`              // 魅力经验值
	PeerageLv      int32       `protobuf:"varint,4,opt,name=PeerageLv,proto3" json:"PeerageLv,omitempty"`           // 爵位等级
	PeerageEndTime int64       `protobuf:"varint,5,opt,name=PeerageEndTime,proto3" json:"PeerageEndTime,omitempty"` // 爵位到期时间
	Equip          *EquipInfo  `protobuf:"bytes,6,opt,name=Equip,proto3" json:"Equip,omitempty"`                    // 装扮
	Gold           string      `protobuf:"bytes,7,opt,name=Gold,proto3" json:"Gold,omitempty"`                      // 可用金币
	Earnings       string      `protobuf:"bytes,8,opt,name=Earnings,proto3" json:"Earnings,omitempty"`              // 可用余额
	LockedGold     string      `protobuf:"bytes,9,opt,name=LockedGold,proto3" json:"LockedGold,omitempty"`          // 锁定金币
	LockedEarnings string      `protobuf:"bytes,10,opt,name=LockedEarnings,proto3" json:"LockedEarnings,omitempty"` // 锁定余额
	Exp            string      `protobuf:"bytes,11,opt,name=Exp,proto3" json:"Exp,omitempty"`                       // 经验值
}

func (x *BagInfo) Reset() {
	*x = BagInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BagInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagInfo) ProtoMessage() {}

func (x *BagInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagInfo.ProtoReflect.Descriptor instead.
func (*BagInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *BagInfo) GetData() []*ItemInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BagInfo) GetRichExp() string {
	if x != nil {
		return x.RichExp
	}
	return ""
}

func (x *BagInfo) GetCharmExp() string {
	if x != nil {
		return x.CharmExp
	}
	return ""
}

func (x *BagInfo) GetPeerageLv() int32 {
	if x != nil {
		return x.PeerageLv
	}
	return 0
}

func (x *BagInfo) GetPeerageEndTime() int64 {
	if x != nil {
		return x.PeerageEndTime
	}
	return 0
}

func (x *BagInfo) GetEquip() *EquipInfo {
	if x != nil {
		return x.Equip
	}
	return nil
}

func (x *BagInfo) GetGold() string {
	if x != nil {
		return x.Gold
	}
	return ""
}

func (x *BagInfo) GetEarnings() string {
	if x != nil {
		return x.Earnings
	}
	return ""
}

func (x *BagInfo) GetLockedGold() string {
	if x != nil {
		return x.LockedGold
	}
	return ""
}

func (x *BagInfo) GetLockedEarnings() string {
	if x != nil {
		return x.LockedEarnings
	}
	return ""
}

func (x *BagInfo) GetExp() string {
	if x != nil {
		return x.Exp
	}
	return ""
}

// 背包内道具
type ItemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`       // 道具id
	Count string `protobuf:"bytes,2,opt,name=Count,proto3" json:"Count,omitempty"` // 道具数量
}

func (x *ItemInfo) Reset() {
	*x = ItemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfo) ProtoMessage() {}

func (x *ItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfo.ProtoReflect.Descriptor instead.
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *ItemInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemInfo) GetCount() string {
	if x != nil {
		return x.Count
	}
	return ""
}

// 装备 装扮
type EquipInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head     int32 `protobuf:"varint,1,opt,name=Head,proto3" json:"Head,omitempty"`         // 头像框
	JoinRoom int32 `protobuf:"varint,2,opt,name=JoinRoom,proto3" json:"JoinRoom,omitempty"` //  加入房间装饰
	Ride     int32 `protobuf:"varint,3,opt,name=Ride,proto3" json:"Ride,omitempty"`         // 坐骑装饰
	Chat     int32 `protobuf:"varint,4,opt,name=Chat,proto3" json:"Chat,omitempty"`         // 聊天气泡装饰
}

func (x *EquipInfo) Reset() {
	*x = EquipInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipInfo) ProtoMessage() {}

func (x *EquipInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipInfo.ProtoReflect.Descriptor instead.
func (*EquipInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *EquipInfo) GetHead() int32 {
	if x != nil {
		return x.Head
	}
	return 0
}

func (x *EquipInfo) GetJoinRoom() int32 {
	if x != nil {
		return x.JoinRoom
	}
	return 0
}

func (x *EquipInfo) GetRide() int32 {
	if x != nil {
		return x.Ride
	}
	return 0
}

func (x *EquipInfo) GetChat() int32 {
	if x != nil {
		return x.Chat
	}
	return 0
}

// 获取用户背包 方法名 GetUserBag
type GetUserBagReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"` // 用户id
}

func (x *GetUserBagReq) Reset() {
	*x = GetUserBagReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBagReq) ProtoMessage() {}

func (x *GetUserBagReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBagReq.ProtoReflect.Descriptor instead.
func (*GetUserBagReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserBagReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 获取用户背包返回
type GetUserBagResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bag *BagInfo `protobuf:"bytes,1,opt,name=Bag,proto3" json:"Bag,omitempty"`
}

func (x *GetUserBagResp) Reset() {
	*x = GetUserBagResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBagResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBagResp) ProtoMessage() {}

func (x *GetUserBagResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBagResp.ProtoReflect.Descriptor instead.
func (*GetUserBagResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserBagResp) GetBag() *BagInfo {
	if x != nil {
		return x.Bag
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

var file_user_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x16,
	0x42, 0x61, 0x6c, 0x6c, 0x6f, 0x6f, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x73, 0x65, 0x72, 0x69,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x22, 0xa5, 0x01, 0x0a, 0x17, 0x42, 0x61, 0x6c, 0x6c, 0x6f,
	0x6f, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x2a, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x64, 0x49, 0x63, 0x6f, 0x6e, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x48, 0x65,
	0x61, 0x64, 0x49, 0x63, 0x6f, 0x6e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x47, 0x6f,
	0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x47, 0x6f, 0x6c, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x5f,
	0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x47, 0x6f, 0x6c, 0x64, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x47, 0x6f, 0x6c, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x47, 0x6f, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x56, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x47, 0x6f, 0x6c, 0x64, 0x45, 0x64, 0x69, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x47, 0x6f, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x47, 0x6f, 0x6c, 0x64, 0x22, 0x2e, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x48, 0x65, 0x61, 0x64, 0x69, 0x6d,
	0x67, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x22, 0xd3, 0x02, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x48, 0x65, 0x61, 0x64, 0x69,
	0x6d, 0x67, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x10, 0x48, 0x65, 0x61,
	0x64, 0x49, 0x63, 0x6f, 0x6e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x48, 0x65, 0x61, 0x64, 0x49, 0x63, 0x6f, 0x6e, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x26, 0x0a, 0x0e, 0x48, 0x65, 0x61, 0x64, 0x49, 0x63, 0x6f,
	0x6e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x48,
	0x65, 0x61, 0x64, 0x49, 0x63, 0x6f, 0x6e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x78, 0x70,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x45, 0x78, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x43,
	0x68, 0x61, 0x72, 0x6d, 0x45, 0x78, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43,
	0x68, 0x61, 0x72, 0x6d, 0x45, 0x78, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x69, 0x63, 0x68, 0x45,
	0x78, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x69, 0x63, 0x68, 0x45, 0x78,
	0x70, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x65, 0x65, 0x72, 0x61, 0x67, 0x65, 0x4c, 0x76, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x50, 0x65, 0x65, 0x72, 0x61, 0x67, 0x65, 0x4c, 0x76, 0x12,
	0x10, 0x0a, 0x03, 0x53, 0x65, 0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x53, 0x65,
	0x78, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x2a, 0x0a,
	0x14, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x79, 0x49, 0x64, 0x22, 0xca, 0x01, 0x0a, 0x15, 0x43, 0x6f,
	0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x34, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x1a, 0x4b, 0x0a, 0x09, 0x44, 0x61, 0x74,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x55, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xab, 0x02, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x6d, 0x75,
	0x6e, 0x69, 0x74, 0x79, 0x55, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x2a, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x64, 0x49, 0x63, 0x6f, 0x6e, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x48, 0x65, 0x61, 0x64,
	0x49, 0x63, 0x6f, 0x6e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x26, 0x0a, 0x0e,
	0x48, 0x65, 0x61, 0x64, 0x49, 0x63, 0x6f, 0x6e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x48, 0x65, 0x61, 0x64, 0x49, 0x63, 0x6f, 0x6e, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x45, 0x78, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x45,
	0x78, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x72, 0x6d, 0x45, 0x78, 0x70, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x68, 0x61, 0x72, 0x6d, 0x45, 0x78, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x52, 0x69, 0x63, 0x68, 0x45, 0x78, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x52, 0x69, 0x63, 0x68, 0x45, 0x78, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x65, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x4c, 0x76, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x50, 0x65, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x4c, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x65, 0x78, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x53, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69, 0x72, 0x74,
	0x68, 0x64, 0x61, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x69, 0x72, 0x74,
	0x68, 0x64, 0x61, 0x79, 0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x46, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x73, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x79,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x22, 0x22, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x69, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x03, 0x49, 0x64, 0x73, 0x22, 0x30, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x69,
	0x6e, 0x66, 0x6f, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0xe4, 0x02, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x44, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x49,
	0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x44, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x2a, 0x0a, 0x10,
	0x48, 0x65, 0x61, 0x64, 0x49, 0x63, 0x6f, 0x6e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x48, 0x65, 0x61, 0x64, 0x49, 0x63, 0x6f, 0x6e,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x65, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x53, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69, 0x72, 0x74, 0x68, 0x64,
	0x61, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x69, 0x72, 0x74, 0x68, 0x64,
	0x61, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x46, 0x61, 0x6e, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x46, 0x61, 0x6e, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x53, 0x74, 0x61, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1a, 0x0a, 0x03, 0x42, 0x61, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x42, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x42, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x43, 0x69, 0x74, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x69, 0x74, 0x79,
	0x22, 0xd0, 0x02, 0x0a, 0x07, 0x42, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x52,
	0x69, 0x63, 0x68, 0x45, 0x78, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x69,
	0x63, 0x68, 0x45, 0x78, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x72, 0x6d, 0x45, 0x78,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x68, 0x61, 0x72, 0x6d, 0x45, 0x78,
	0x70, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x65, 0x65, 0x72, 0x61, 0x67, 0x65, 0x4c, 0x76, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x50, 0x65, 0x65, 0x72, 0x61, 0x67, 0x65, 0x4c, 0x76, 0x12,
	0x26, 0x0a, 0x0e, 0x50, 0x65, 0x65, 0x72, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x50, 0x65, 0x65, 0x72, 0x61, 0x67, 0x65,
	0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x45, 0x71, 0x75, 0x69, 0x70,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x05, 0x45, 0x71, 0x75, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x47, 0x6f, 0x6c,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x47, 0x6f, 0x6c, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x45, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x45, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x4c, 0x6f, 0x63,
	0x6b, 0x65, 0x64, 0x47, 0x6f, 0x6c, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4c,
	0x6f, 0x63, 0x6b, 0x65, 0x64, 0x47, 0x6f, 0x6c, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x4c, 0x6f, 0x63,
	0x6b, 0x65, 0x64, 0x45, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x45, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x78, 0x70, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x45, 0x78, 0x70, 0x22, 0x30, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x63, 0x0a, 0x09, 0x45, 0x71, 0x75, 0x69, 0x70, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x48, 0x65, 0x61, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f,
	0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f,
	0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x69, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x52, 0x69, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x68, 0x61, 0x74, 0x22, 0x1f, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x67, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a,
	0x03, 0x42, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x42, 0x61, 0x67, 0x42, 0x1d, 0x5a, 0x1b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x69, 0x61, 0x7a, 0x68, 0x65, 0x2d, 0x78,
	0x2f, 0x70, 0x62, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData = file_user_proto_rawDesc
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_proto_rawDescData)
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_user_proto_goTypes = []interface{}{
	(*BalloonGameUserinfoReq)(nil),        // 0: BalloonGameUserinfoReq
	(*BalloonGameUserinfoResp)(nil),       // 1: BalloonGameUserinfoResp
	(*UserGoldEditReq)(nil),               // 2: UserGoldEditReq
	(*UserGoldEditResp)(nil),              // 3: UserGoldEditResp
	(*GetUserNicknameHeadimgUrlReq)(nil),  // 4: GetUserNicknameHeadimgUrlReq
	(*GetUserNicknameHeadimgUrlResp)(nil), // 5: GetUserNicknameHeadimgUrlResp
	(*CommunityUserListReq)(nil),          // 6: CommunityUserListReq
	(*CommunityUserListResp)(nil),         // 7: CommunityUserListResp
	(*CommunityUserinfo)(nil),             // 8: CommunityUserinfo
	(*GetMyFollowsReq)(nil),               // 9: GetMyFollowsReq
	(*GetMyFollowsResp)(nil),              // 10: GetMyFollowsResp
	(*GetUserinfoReq)(nil),                // 11: GetUserinfoReq
	(*GetUserinfoResp)(nil),               // 12: GetUserinfoResp
	(*Userinfo)(nil),                      // 13: Userinfo
	(*BagInfo)(nil),                       // 14: BagInfo
	(*ItemInfo)(nil),                      // 15: ItemInfo
	(*EquipInfo)(nil),                     // 16: EquipInfo
	(*GetUserBagReq)(nil),                 // 17: GetUserBagReq
	(*GetUserBagResp)(nil),                // 18: GetUserBagResp
	nil,                                   // 19: CommunityUserListResp.DataEntry
}
var file_user_proto_depIdxs = []int32{
	19, // 0: CommunityUserListResp.Data:type_name -> CommunityUserListResp.DataEntry
	13, // 1: GetUserinfoResp.Data:type_name -> Userinfo
	14, // 2: Userinfo.Bag:type_name -> BagInfo
	15, // 3: BagInfo.Data:type_name -> ItemInfo
	16, // 4: BagInfo.Equip:type_name -> EquipInfo
	14, // 5: GetUserBagResp.Bag:type_name -> BagInfo
	8,  // 6: CommunityUserListResp.DataEntry.value:type_name -> CommunityUserinfo
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalloonGameUserinfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalloonGameUserinfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGoldEditReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGoldEditResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserNicknameHeadimgUrlReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserNicknameHeadimgUrlResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityUserListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityUserListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityUserinfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyFollowsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyFollowsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserinfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserinfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Userinfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BagInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBagReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBagResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_rawDesc = nil
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
